### YamlMime:UniversalReference
ms.openlocfilehash: 777051058935475aebf2055932882ec0cd21fea9
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 12/13/2018
ms.locfileid: "52135171"
items:
- uid: azure-servicefabric.TestErrorChaosEvent
  name: TestErrorChaosEvent
  fullName: TestErrorChaosEvent
  children:
  - azure-servicefabric.TestErrorChaosEvent.reason
  langs:
  - typeScript
  type: interface
  summary: >-
    Descreve um evento de caos que é gerado quando ocorre um evento inesperado no mecanismo de Chaos.

    Por exemplo, devido ao instantâneo de cluster que está sendo inconsistentes, ao mesmo tempo em que a falha de uma entidade, o Chaos encontrado que a entidade já falha – que seria um evento inesperado.
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.TestErrorChaosEvent.reason
  name: reason
  fullName: reason
  children: []
  langs:
  - typeScript
  type: property
  summary: Descreve por que TestErrorChaosEvent foi gerado. Por exemplo, o Chaos tenta uma partição de falha, mas localiza a que a partição não é mais tolerante a falhas, então um TestErrorEvent seja gerado com o motivo informando que a partição não tolerante a falhas.
  optional: true
  syntax:
    content: 'reason?: string'
    return:
      type:
      - string
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
